// frontend/nuxt/components/TaskComponent.vue
<template>
  <div class="task">
    <button class="concluida"></button>
    <p>Nome Task</p>
    <button class="updateTaskElement" id="updateTask">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        strokeWidth="1.5"
        stroke="currentColor"
        class="w-6 h-6"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10"
        ></path>
      </svg>
    </button>
    <button class="deleteTaskElement" id="deletarTask">
      <img src="/icons/lixo.svg" alt="excluir tarefa" width="16px" height="16px" />
    </button>
  </div>
</template>

<script lang="ts">
import './task.scss'
</script>

// nextjs/src/components/task.tsx
import style from './task.module.scss';

export default function Task(){
    return (
        <div className={style.task}>
            <button className={style.concluida}></button>
            <p>Nome Task</p>
            <button className={style.updateTaskElement} id="updateTask">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="w-6 h-6">
                    <path strokeLinecap="round" strokeLinejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10"></path>
                </svg>
            </button>
            <button className="deleteTaskElement" id="deletarTask">
                <img src="./icons/lixo.svg" alt="excluir tarefa" width="16px" height="16px"/>
            </button>
        </div>
    )
}
