// frontend/nuxt/components/TaskListComponent.vue
<template>
  <div class="taskList">
    <div>
      <div>
        <div class="created">
          <p>Tarefas criadas</p>
          <span>0</span>
        </div>
        <div class="concluded">
          <p>Concluídas</p>
          <span>0</span>
        </div>
      </div>
      <hr />
      <div>
        <TaskComponent></TaskComponent>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import './task-list.scss'
</script>

// svelte/src/components/website/tasklist.svelte
<script lang="ts">
    import Task from './task.svelte';
    import './task-list.scss';
</script>

<div class="taskList">
    <div>
    <div>
        <div class="created">
        <p>Tarefas criadas</p>
        <span>0</span>
        </div>
        <div class="concluded">
        <p>Concluídas</p>
        <span>0</span>
        </div>
    </div>
    <hr />
    <div>
        <Task></Task>
    </div>
    </div>
</div>
